
version: "3.9"
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "8080:4173"
    restart: unless-stopped
